# Generated by Django 3.2.5 on 2021-12-19 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_goods_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.user')),
                ('seller_name', models.CharField(max_length=25, verbose_name='店铺名称')),
                ('goods_number', models.IntegerField(default=0, verbose_name='数量')),
                ('sum_price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='总价')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goods', verbose_name='商品ID')),
            ],
        ),
    ]
