# Generated by Django 3.2.5 on 2021-12-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sum_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='goods_name',
            field=models.CharField(default='', max_length=50, verbose_name='商品名称'),
        ),
        migrations.AddField(
            model_name='cart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=20, null=True, verbose_name='单价'),
        ),
    ]
