# Generated by Django 3.2.5 on 2021-12-19 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211219_1726'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
