# Generated by Django 3.2.5 on 2021-12-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='img',
            field=models.ImageField(default='', upload_to='', verbose_name='商品图片'),
        ),
    ]
