# Generated by Django 3.2.5 on 2021-12-19 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_cart_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addressee',
        ),
        migrations.AddField(
            model_name='order',
            name='address_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.address'),
        ),
    ]
