# Generated by Django 3.2.5 on 2021-12-19 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211219_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
