# Generated by Django 3.2.5 on 2021-12-20 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_good_number_order_goods_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='item_img',
            field=models.ImageField(default='item_image/default.jpg', upload_to='g_images/', verbose_name='图片'),
        ),
    ]
