# Generated by Django 3.2.5 on 2021-12-20 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_goods_item_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
    ]
