# Generated by Django 3.2.5 on 2021-12-20 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_context', models.TextField(max_length=500, verbose_name='评论内容')),
                ('user_name', models.CharField(max_length=10, verbose_name='评论人')),
                ('post_time', models.DateTimeField(verbose_name='发布时间')),
                ('goods_name', models.CharField(max_length=50, verbose_name='评论商品名称')),
                ('post_goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.goods')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
