# Generated by Django 3.2.5 on 2021-12-20 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order',
        ),
    ]
