# Generated by Django 3.2.5 on 2021-12-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211220_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='goods_id',
            field=models.IntegerField(default=0, verbose_name='商品ID'),
        ),
    ]
