# Generated by Django 3.2.5 on 2021-12-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_id',
            new_name='address',
        ),
    ]
