# Generated by Django 3.2.5 on 2021-12-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_address_id_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.seller'),
        ),
    ]
