# Generated by Django 3.2.5 on 2021-12-20 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_goods_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.seller'),
        ),
    ]
