# Generated by Django 3.2.5 on 2021-12-20 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20211220_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='order_id',
        ),
    ]
