# Generated by Django 3.2.5 on 2021-12-20 23:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_rename_order_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_introduction',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='商品简介ya', max_length=50, verbose_name='简介'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='item_img',
            field=models.ImageField(default='item_img/default.jpg', upload_to='g_images/', verbose_name='图片'),
        ),
    ]
