# Generated by Django 3.2.5 on 2022-02-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20220227_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='用户余额'),
        ),
    ]
